const RECIPE_MEAL_LABELS = { breakfast: 'Завтрак', lunch: 'Обед', dinner: 'Ужин', snack: 'Перекус' };
        const RECIPE_MEAL_KEYS = { 'Завтрак': 'breakfast', 'Обед': 'lunch', 'Ужин': 'dinner', 'Перекус': 'snack' };
        const RECIPE_GOAL_LABELS = { cutting: 'Сушка', weight_loss: 'Похудение', maintenance: 'Поддержание', bulking: 'Набор', muscle_gain: 'Рост мышц' };
        const RECIPE_NUTRITION_LABELS = { high_protein: 'Высокий белок', low_calorie: 'Низкокалорийное', low_carb: 'Low carb', low_fat: 'Мало жиров', balanced: 'Баланс', quick: 'Быстро', meal_prep: 'Заготовка' };
        const VALID_INGREDIENT_UNITS = ['g', 'ml', 'pcs'];
        const VALID_INGREDIENT_CATEGORIES = ['meat', 'fish', 'dairy', 'eggs', 'grains', 'vegetables', 'fruits', 'nuts', 'oils', 'spices', 'other'];

        function ing(name, amount, unit, category) {
            return { name, amount, unit, category };
        }

        function ingredientAmountToGrams(name, amount, unit, explicitGrams) {
            if (Number(explicitGrams) > 0) return Number(explicitGrams);
            const value = Number(amount) || 0;
            const key = String(unit || 'g').toLowerCase();
            if (key === 'ml') return value;
            if (key !== 'pcs') return value;
            return /(яйц|egg)/i.test(String(name || '')) ? value * 55 : value;
        }

        const STARTER_RECIPES = [
            { id: 1, title: 'Овсяноблин с творогом', description: 'Сытный белковый завтрак с овсянкой, яйцом и творогом.', mealType: 'breakfast', goalTags: ['weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','balanced','quick'], calories: 146, protein: 12.7, fat: 5.3, carbs: 12.1, cookingTime: 15, servings: 1, ingredients: [ing('овсяные хлопья',40,'g','grains'),ing('яйцо',1,'pcs','eggs'),ing('творог 5%',120,'g','dairy'),ing('молоко 1.5%',40,'ml','dairy'),ing('соль',1,'g','spices')], instructions: ['Смешайте овсяные хлопья, яйцо, молоко и соль.','Выпекайте блин на антипригарной сковороде 3-4 минуты с каждой стороны.','Добавьте творог внутрь и сложите пополам.'], storage: 'Лучше есть сразу; в холодильнике до 24 часов.', image: 'https://source.unsplash.com/640x480/?oatmeal,pancake,cottage-cheese', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['овсяноблин','творог','завтрак','овсянка','белок'] },
            { id: 2, title: 'Омлет с индейкой и шпинатом', description: 'Легкий омлет с постной индейкой и зеленью.', mealType: 'breakfast', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_carb','quick'], calories: 136, protein: 15.4, fat: 7.2, carbs: 1.6, cookingTime: 12, servings: 1, ingredients: [ing('яйца',2,'pcs','eggs'),ing('филе индейки',80,'g','meat'),ing('шпинат',50,'g','vegetables'),ing('молоко 1.5%',30,'ml','dairy'),ing('оливковое масло',3,'g','oils')], instructions: ['Нарежьте индейку и прогрейте на сковороде.','Добавьте шпинат на 1 минуту.','Влейте яйца с молоком и готовьте под крышкой до схватывания.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?omelette,spinach,turkey', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['омлет','индейка','шпинат','яйца','low carb'] },
            { id: 3, title: 'Белковые сырники без сахара', description: 'Творожные сырники с рисовой мукой и без добавленного сахара.', mealType: 'breakfast', goalTags: ['weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','balanced','meal_prep'], calories: 164, protein: 16.4, fat: 5.0, carbs: 12.4, cookingTime: 25, servings: 2, ingredients: [ing('творог 2%',300,'g','dairy'),ing('яйцо',1,'pcs','eggs'),ing('рисовая мука',35,'g','grains'),ing('подсластитель',1,'g','other'),ing('ваниль',1,'g','spices')], instructions: ['Смешайте творог, яйцо, муку, подсластитель и ваниль.','Сформируйте сырники влажными руками.','Готовьте на антипригарной сковороде или запеките при 180 градусах 18 минут.'], storage: 'Холодильник 2-3 дня.', image: 'https://source.unsplash.com/640x480/?cottage-cheese,pancakes,healthy', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['сырники','творог','без сахара','meal prep','белковые'] },
            { id: 4, title: 'Греческий йогурт с ягодами', description: 'Быстрый холодный завтрак или перекус с ягодами и семенами.', mealType: 'breakfast', goalTags: ['cutting','weight_loss','maintenance'], nutritionTags: ['high_protein','low_calorie','quick'], calories: 94, protein: 8.5, fat: 2.7, carbs: 8.7, cookingTime: 5, servings: 1, ingredients: [ing('греческий йогурт 2%',200,'g','dairy'),ing('ягоды',80,'g','fruits'),ing('семена чиа',8,'g','nuts'),ing('мед',5,'g','other')], instructions: ['Выложите йогурт в миску.','Добавьте ягоды, чиа и немного меда.','Перемешайте или оставьте слоями.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?greek-yogurt,berries', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['йогурт','ягоды','быстро','завтрак','низкокалорийно'] },
            { id: 5, title: 'Протеиновая овсянка', description: 'Овсянка с молоком, бананом и протеином после тренировки.', mealType: 'breakfast', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','balanced','quick'], calories: 139, protein: 10.3, fat: 3.1, carbs: 18.4, cookingTime: 10, servings: 1, ingredients: [ing('овсяные хлопья',55,'g','grains'),ing('молоко 1.5%',180,'ml','dairy'),ing('сывороточный протеин',25,'g','dairy'),ing('банан',70,'g','fruits'),ing('корица',1,'g','spices')], instructions: ['Сварите овсянку на молоке 5-6 минут.','Снимите с огня и вмешайте протеин.','Добавьте банан и корицу.'], storage: 'Холодильник до 24 часов, разогревать с небольшим количеством молока.', image: 'https://source.unsplash.com/640x480/?protein,oatmeal,banana', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['овсянка','протеин','банан','после тренировки','набор'] },
            { id: 6, title: 'Яйца с авокадо и цельнозерновым тостом', description: 'Сбалансированный завтрак с полезными жирами и тостом.', mealType: 'breakfast', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['balanced','quick'], calories: 184, protein: 8.0, fat: 11.5, carbs: 12.8, cookingTime: 10, servings: 1, ingredients: [ing('яйца',2,'pcs','eggs'),ing('авокадо',70,'g','fruits'),ing('цельнозерновой хлеб',40,'g','grains'),ing('лимонный сок',5,'ml','other'),ing('соль',1,'g','spices')], instructions: ['Отварите или пожарьте яйца без лишнего масла.','Разомните авокадо с лимонным соком и солью.','Подайте с цельнозерновым тостом.'], storage: 'Лучше есть сразу.', image: 'https://source.unsplash.com/640x480/?eggs,avocado,toast', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['яйца','авокадо','тост','завтрак','баланс'] },
            { id: 7, title: 'Протеиновые панкейки', description: 'Мягкие панкейки из овсянки, банана и протеина.', mealType: 'breakfast', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','balanced','meal_prep'], calories: 171, protein: 13.0, fat: 4.6, carbs: 18.4, cookingTime: 20, servings: 2, ingredients: [ing('овсяные хлопья',60,'g','grains'),ing('сывороточный протеин',30,'g','dairy'),ing('банан',100,'g','fruits'),ing('яйцо',1,'pcs','eggs'),ing('молоко 1.5%',80,'ml','dairy')], instructions: ['Пробейте ингредиенты блендером.','Выпекайте небольшие панкейки на антипригарной сковороде.','Подавайте с ягодами или йогуртом.'], storage: 'Холодильник 2 дня, морозилка до 30 дней.', image: 'https://source.unsplash.com/640x480/?protein,pancakes', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['панкейки','протеин','овсянка','завтрак','meal prep'] },
            { id: 8, title: 'Творожная запеканка high protein', description: 'Запеканка из творога и йогурта для завтраков на несколько дней.', mealType: 'breakfast', goalTags: ['weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','balanced','meal_prep'], calories: 127, protein: 15.2, fat: 3.8, carbs: 7.5, cookingTime: 40, servings: 4, ingredients: [ing('творог 2%',500,'g','dairy'),ing('греческий йогурт 2%',120,'g','dairy'),ing('яйца',2,'pcs','eggs'),ing('манная крупа',35,'g','grains'),ing('ягоды',80,'g','fruits')], instructions: ['Смешайте творог, йогурт, яйца и манку.','Добавьте ягоды.','Запекайте 30-35 минут при 180 градусах.'], storage: 'Холодильник 3 дня, морозилка до 30 дней.', image: 'https://source.unsplash.com/640x480/?cottage-cheese,casserole,berries', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['запеканка','творог','high protein','завтрак','заготовка'] },

            { id: 9, title: 'Куриный стейк с брокколи', description: 'Постное филе с брокколи и легкой заправкой.', mealType: 'lunch', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_calorie','low_carb','meal_prep'], calories: 119, protein: 18.7, fat: 3.7, carbs: 3.4, cookingTime: 25, servings: 1, ingredients: [ing('куриное филе',180,'g','meat'),ing('брокколи',200,'g','vegetables'),ing('оливковое масло',7,'g','oils'),ing('лимонный сок',10,'ml','other'),ing('паприка',2,'g','spices')], instructions: ['Замаринуйте филе с паприкой и лимоном.','Обжарьте или запеките до готовности.','Брокколи приготовьте на пару и добавьте масло.'], storage: 'Холодильник 3 дня.', image: 'https://source.unsplash.com/640x480/?chicken,broccoli,healthy', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['курица','брокколи','обед','сушка','low calorie'] },
            { id: 10, title: 'Гречка с куриным филе', description: 'Классический сбалансированный обед с крупой и белком.', mealType: 'lunch', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','balanced','meal_prep'], calories: 139, protein: 13.8, fat: 3.0, carbs: 14.8, cookingTime: 30, servings: 2, ingredients: [ing('гречка вареная',200,'g','grains'),ing('куриное филе',220,'g','meat'),ing('морковь',60,'g','vegetables'),ing('лук',40,'g','vegetables'),ing('оливковое масло',8,'g','oils')], instructions: ['Отварите гречку.','Куриное филе нарежьте и потушите с луком и морковью.','Смешайте с гречкой и прогрейте.'], storage: 'Холодильник 3 дня, морозилка до 30 дней.', image: 'https://source.unsplash.com/640x480/?buckwheat,chicken', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['гречка','курица','обед','meal prep','масса'] },
            { id: 11, title: 'Индейка с булгуром', description: 'Постная индейка с булгуром и овощами.', mealType: 'lunch', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','balanced','meal_prep'], calories: 130, protein: 13.2, fat: 2.8, carbs: 14.1, cookingTime: 30, servings: 2, ingredients: [ing('филе индейки',220,'g','meat'),ing('булгур вареный',220,'g','grains'),ing('кабачок',100,'g','vegetables'),ing('томат',80,'g','vegetables'),ing('оливковое масло',8,'g','oils')], instructions: ['Отварите булгур.','Индейку нарежьте и обжарьте с овощами.','Соедините с булгуром и прогрейте 2 минуты.'], storage: 'Холодильник 3 дня.', image: 'https://source.unsplash.com/640x480/?turkey,bulgur,bowl', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['индейка','булгур','обед','белок','заготовка'] },
            { id: 12, title: 'Лосось с овощами', description: 'Запеченный лосось с овощным гарниром.', mealType: 'lunch', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','balanced','low_carb'], calories: 151, protein: 12.1, fat: 9.2, carbs: 4.3, cookingTime: 25, servings: 1, ingredients: [ing('лосось',160,'g','fish'),ing('брокколи',120,'g','vegetables'),ing('болгарский перец',80,'g','vegetables'),ing('оливковое масло',5,'g','oils'),ing('лимон',20,'g','fruits')], instructions: ['Выложите лосось и овощи в форму.','Добавьте масло, лимон и специи.','Запекайте 18-20 минут при 190 градусах.'], storage: 'Холодильник 2 дня.', image: 'https://source.unsplash.com/640x480/?salmon,vegetables', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['лосось','овощи','обед','рыба','омега'] },
            { id: 13, title: 'Тунец с киноа', description: 'Боул с тунцом, киноа, овощами и йогуртовой заправкой.', mealType: 'lunch', goalTags: ['weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','balanced','quick'], calories: 124, protein: 12.6, fat: 3.0, carbs: 11.2, cookingTime: 15, servings: 1, ingredients: [ing('тунец в собственном соку',120,'g','fish'),ing('киноа вареная',140,'g','grains'),ing('огурец',80,'g','vegetables'),ing('томат',80,'g','vegetables'),ing('греческий йогурт 2%',40,'g','dairy')], instructions: ['Смешайте киноа с овощами.','Добавьте тунец.','Заправьте греческим йогуртом со специями.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?tuna,quinoa,bowl', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['тунец','киноа','боул','обед','быстро'] },
            { id: 14, title: 'Рис с курицей терияки light', description: 'Облегченная версия риса с курицей и соусом терияки.', mealType: 'lunch', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','balanced','meal_prep'], calories: 139, protein: 12.9, fat: 2.2, carbs: 16.3, cookingTime: 25, servings: 2, ingredients: [ing('куриное филе',220,'g','meat'),ing('рис вареный',240,'g','grains'),ing('соевый соус light',20,'ml','other'),ing('мед',8,'g','other'),ing('стручковая фасоль',120,'g','vegetables')], instructions: ['Нарежьте курицу и обжарьте на антипригарной сковороде.','Добавьте соевый соус, мед и фасоль.','Подавайте с рисом.'], storage: 'Холодильник 3 дня.', image: 'https://source.unsplash.com/640x480/?chicken,rice,teriyaki', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['рис','курица','терияки','обед','light'] },
            { id: 15, title: 'Bowl с креветками', description: 'Легкий боул с креветками, рисом, овощами и авокадо.', mealType: 'lunch', goalTags: ['weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','balanced','quick'], calories: 119, protein: 10.2, fat: 3.8, carbs: 10.5, cookingTime: 20, servings: 1, ingredients: [ing('креветки',150,'g','fish'),ing('рис вареный',120,'g','grains'),ing('огурец',80,'g','vegetables'),ing('авокадо',50,'g','fruits'),ing('соевый соус light',15,'ml','other')], instructions: ['Креветки быстро обжарьте или отварите.','Соберите рис, овощи и авокадо в миску.','Добавьте креветки и соевый соус.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?shrimp,bowl,rice', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['креветки','bowl','боул','рис','обед'] },
            { id: 16, title: 'Фрикадельки из индейки', description: 'Запеченные фрикадельки из индейки с томатным соусом.', mealType: 'lunch', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_fat','meal_prep'], calories: 128, protein: 16.9, fat: 4.1, carbs: 5.2, cookingTime: 35, servings: 3, ingredients: [ing('фарш индейки',450,'g','meat'),ing('яйцо',1,'pcs','eggs'),ing('овсяные хлопья',30,'g','grains'),ing('томатная пассата',200,'g','vegetables'),ing('чеснок',5,'g','spices')], instructions: ['Смешайте фарш, яйцо, овсянку и специи.','Сформируйте фрикадельки.','Запекайте с томатной пассатой 25 минут при 190 градусах.'], storage: 'Холодильник 3 дня, морозилка до 30 дней.', image: 'https://source.unsplash.com/640x480/?turkey,meatballs,healthy', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['фрикадельки','индейка','meal prep','обед','фарш'] },

            { id: 17, title: 'Салат с тунцом и яйцом', description: 'Белковый салат без тяжелой заправки.', mealType: 'dinner', goalTags: ['cutting','weight_loss','maintenance'], nutritionTags: ['high_protein','low_calorie','low_carb','quick'], calories: 105, protein: 13.6, fat: 4.5, carbs: 2.2, cookingTime: 10, servings: 1, ingredients: [ing('тунец в собственном соку',120,'g','fish'),ing('яйцо',1,'pcs','eggs'),ing('листья салата',80,'g','vegetables'),ing('огурец',100,'g','vegetables'),ing('греческий йогурт 2%',35,'g','dairy')], instructions: ['Отварите яйцо.','Смешайте салат, огурец и тунец.','Добавьте яйцо и йогуртовую заправку.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?tuna,egg,salad', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['салат','тунец','яйцо','ужин','low calorie'] },
            { id: 18, title: 'Лосось с брокколи', description: 'Насыщающий ужин с рыбой и брокколи.', mealType: 'dinner', goalTags: ['maintenance','muscle_gain'], nutritionTags: ['high_protein','low_carb','balanced'], calories: 157, protein: 13.4, fat: 9.5, carbs: 3.3, cookingTime: 22, servings: 1, ingredients: [ing('лосось',150,'g','fish'),ing('брокколи',180,'g','vegetables'),ing('оливковое масло',5,'g','oils'),ing('лимонный сок',10,'ml','other'),ing('перец',1,'g','spices')], instructions: ['Запеките лосось с лимоном и перцем.','Брокколи приготовьте на пару.','Подайте вместе, добавив немного масла.'], storage: 'Холодильник 2 дня.', image: 'https://source.unsplash.com/640x480/?salmon,broccoli', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['лосось','брокколи','ужин','рыба','low carb'] },
            { id: 19, title: 'Омлет с овощами', description: 'Быстрый легкий ужин из яиц и овощей.', mealType: 'dinner', goalTags: ['cutting','weight_loss','maintenance'], nutritionTags: ['low_calorie','low_carb','quick'], calories: 93, protein: 7.6, fat: 5.7, carbs: 3.0, cookingTime: 12, servings: 1, ingredients: [ing('яйца',2,'pcs','eggs'),ing('болгарский перец',70,'g','vegetables'),ing('томат',80,'g','vegetables'),ing('шпинат',40,'g','vegetables'),ing('молоко 1.5%',30,'ml','dairy')], instructions: ['Нарежьте овощи и прогрейте на сковороде.','Влейте яйца с молоком.','Готовьте под крышкой до готовности.'], storage: 'Лучше есть сразу, холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?vegetable,omelette', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['омлет','овощи','ужин','быстро','низкокалорийно'] },
            { id: 20, title: 'Индейка с салатом', description: 'Постная индейка с большим овощным салатом.', mealType: 'dinner', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_calorie','low_carb'], calories: 103, protein: 15.5, fat: 3.0, carbs: 3.2, cookingTime: 20, servings: 1, ingredients: [ing('филе индейки',170,'g','meat'),ing('листья салата',80,'g','vegetables'),ing('огурец',100,'g','vegetables'),ing('томат',100,'g','vegetables'),ing('оливковое масло',5,'g','oils')], instructions: ['Индейку запеките или обжарьте без лишнего масла.','Нарежьте овощи.','Соберите салат и добавьте индейку сверху.'], storage: 'Индейка хранится 3 дня, салат лучше собирать перед едой.', image: 'https://source.unsplash.com/640x480/?turkey,salad,healthy', isMealPrep: true, isFreezerFriendly: false, searchKeywords: ['индейка','салат','ужин','сушка','белок'] },
            { id: 21, title: 'Креветки с овощами', description: 'Быстрый ужин с креветками и овощной смесью.', mealType: 'dinner', goalTags: ['cutting','weight_loss','maintenance'], nutritionTags: ['high_protein','low_calorie','low_carb','quick'], calories: 82, protein: 11.8, fat: 2.2, carbs: 3.8, cookingTime: 15, servings: 1, ingredients: [ing('креветки',170,'g','fish'),ing('брокколи',100,'g','vegetables'),ing('кабачок',100,'g','vegetables'),ing('болгарский перец',80,'g','vegetables'),ing('оливковое масло',5,'g','oils')], instructions: ['Овощи быстро обжарьте или потушите.','Добавьте креветки на 3-4 минуты.','Приправьте солью, перцем и лимоном.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?shrimp,vegetables', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['креветки','овощи','ужин','low carb','быстро'] },
            { id: 22, title: 'Запеченная рыба', description: 'Белая рыба с овощами и лимоном.', mealType: 'dinner', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_calorie','low_fat','meal_prep'], calories: 86, protein: 13.8, fat: 2.1, carbs: 3.2, cookingTime: 25, servings: 2, ingredients: [ing('филе белой рыбы',300,'g','fish'),ing('кабачок',150,'g','vegetables'),ing('томат',100,'g','vegetables'),ing('оливковое масло',6,'g','oils'),ing('лимон',20,'g','fruits')], instructions: ['Выложите рыбу и овощи в форму.','Добавьте масло, лимон и специи.','Запекайте 20 минут при 190 градусах.'], storage: 'Холодильник 2 дня.', image: 'https://source.unsplash.com/640x480/?baked,fish,vegetables', isMealPrep: true, isFreezerFriendly: false, searchKeywords: ['рыба','запеченная','ужин','low fat','сушка'] },
            { id: 23, title: 'Белковый салат', description: 'Салат с курицей, яйцом и йогуртовой заправкой.', mealType: 'dinner', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_calorie','quick'], calories: 112, protein: 14.3, fat: 4.1, carbs: 3.7, cookingTime: 15, servings: 1, ingredients: [ing('куриное филе готовое',120,'g','meat'),ing('яйцо',1,'pcs','eggs'),ing('листья салата',70,'g','vegetables'),ing('огурец',80,'g','vegetables'),ing('греческий йогурт 2%',40,'g','dairy')], instructions: ['Нарежьте готовую курицу и яйцо.','Смешайте с салатом и огурцом.','Заправьте йогуртом со специями.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?protein,salad,chicken', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['белковый салат','курица','яйцо','ужин','high protein'] },
            { id: 24, title: 'ПП-шаурма', description: 'Домашняя шаурма с курицей, овощами и йогуртовым соусом.', mealType: 'dinner', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','balanced','quick'], calories: 146, protein: 12.2, fat: 4.3, carbs: 14.2, cookingTime: 20, servings: 1, ingredients: [ing('цельнозерновая тортилья',60,'g','grains'),ing('куриное филе готовое',120,'g','meat'),ing('капуста',80,'g','vegetables'),ing('огурец',60,'g','vegetables'),ing('греческий йогурт 2%',50,'g','dairy')], instructions: ['Смешайте йогурт со специями.','Выложите курицу, овощи и соус на тортилью.','Сверните и прогрейте на сухой сковороде.'], storage: 'Лучше есть сразу; начинку можно хранить 2 дня.', image: 'https://source.unsplash.com/640x480/?healthy,wrap,chicken', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['пп шаурма','шаурма','тортилья','курица','ужин'] },

            { id: 25, title: 'Протеиновый коктейль', description: 'Быстрый коктейль на молоке с протеином и бананом.', mealType: 'snack', goalTags: ['maintenance','bulking','muscle_gain'], nutritionTags: ['high_protein','quick'], calories: 93, protein: 9.0, fat: 1.6, carbs: 10.4, cookingTime: 3, servings: 1, ingredients: [ing('молоко 1.5%',250,'ml','dairy'),ing('сывороточный протеин',30,'g','dairy'),ing('банан',60,'g','fruits'),ing('лед',50,'g','other')], instructions: ['Сложите ингредиенты в блендер.','Взбейте до однородности.','Выпейте сразу после приготовления.'], storage: 'Лучше пить сразу.', image: 'https://source.unsplash.com/640x480/?protein,shake,banana', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['протеиновый коктейль','протеин','перекус','банан','shake'] },
            { id: 26, title: 'Творог с ягодами', description: 'Простой белковый перекус с ягодами.', mealType: 'snack', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_calorie','quick'], calories: 100, protein: 13.3, fat: 2.6, carbs: 5.8, cookingTime: 3, servings: 1, ingredients: [ing('творог 2%',180,'g','dairy'),ing('ягоды',70,'g','fruits'),ing('корица',1,'g','spices')], instructions: ['Выложите творог в миску.','Добавьте ягоды и корицу.','Перемешайте по желанию.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?cottage-cheese,berries', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['творог','ягоды','перекус','белок','быстро'] },
            { id: 27, title: 'Протеиновый пудинг', description: 'Густой йогуртовый пудинг с протеином и какао.', mealType: 'snack', goalTags: ['weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_calorie','quick'], calories: 111, protein: 14.4, fat: 2.4, carbs: 7.0, cookingTime: 5, servings: 1, ingredients: [ing('греческий йогурт 2%',180,'g','dairy'),ing('сывороточный протеин',25,'g','dairy'),ing('какао',6,'g','other'),ing('ягоды',40,'g','fruits')], instructions: ['Смешайте йогурт, протеин и какао.','Оставьте на 5 минут для густоты.','Добавьте ягоды сверху.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?protein,pudding,cocoa', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['пудинг','протеин','какао','перекус','десерт'] },
            { id: 28, title: 'Вареные яйца', description: 'Минимальный перекус с понятным белком и жирами.', mealType: 'snack', goalTags: ['cutting','weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','low_carb','meal_prep'], calories: 143, protein: 12.6, fat: 9.5, carbs: 0.8, cookingTime: 10, servings: 1, ingredients: [ing('яйца',2,'pcs','eggs'),ing('соль',1,'g','spices')], instructions: ['Положите яйца в холодную воду.','Варите 8-10 минут после закипания.','Остудите и очистите.'], storage: 'В скорлупе в холодильнике до 3 дней.', image: 'https://source.unsplash.com/640x480/?boiled,eggs', isMealPrep: true, isFreezerFriendly: false, searchKeywords: ['яйца','вареные яйца','перекус','low carb','meal prep'] },
            { id: 29, title: 'Йогурт с какао', description: 'Легкий шоколадный перекус без сахара.', mealType: 'snack', goalTags: ['cutting','weight_loss','maintenance'], nutritionTags: ['high_protein','low_calorie','quick'], calories: 83, protein: 8.1, fat: 2.4, carbs: 6.8, cookingTime: 3, servings: 1, ingredients: [ing('греческий йогурт 2%',200,'g','dairy'),ing('какао',6,'g','other'),ing('подсластитель',1,'g','other'),ing('корица',1,'g','spices')], instructions: ['Смешайте йогурт с какао и подсластителем.','Добавьте корицу.','Подавайте охлажденным.'], storage: 'Холодильник до 24 часов.', image: 'https://source.unsplash.com/640x480/?yogurt,cocoa,chocolate', isMealPrep: false, isFreezerFriendly: false, searchKeywords: ['йогурт','какао','перекус','шоколадный','низкокалорийно'] },
            { id: 30, title: 'Эдамаме', description: 'Растительный белковый перекус с клетчаткой.', mealType: 'snack', goalTags: ['weight_loss','maintenance','muscle_gain'], nutritionTags: ['high_protein','balanced','quick'], calories: 121, protein: 11.9, fat: 5.2, carbs: 8.9, cookingTime: 8, servings: 1, ingredients: [ing('эдамаме',150,'g','vegetables'),ing('соль',1,'g','spices'),ing('лимонный сок',5,'ml','other')], instructions: ['Отварите эдамаме 5-6 минут.','Посолите и добавьте лимонный сок.','Подавайте теплым или охлажденным.'], storage: 'Холодильник 2 дня.', image: 'https://source.unsplash.com/640x480/?edamame,healthy,snack', isMealPrep: true, isFreezerFriendly: true, searchKeywords: ['эдамаме','перекус','растительный белок','бобы','meal prep'] }
        ];

